### ISSUE TITLE
refactor entire code base

### ISSUE THREAD

**Issue by 98sean98** [rcltech/website#3]
there are a couple of warnings resolved forcefully in #2 where
`<a href="">` tags to not have valid `href` attributes, the recommended solution is to use other html elements like `button` to achieve the desired css styling

the code base needs cleaning up, @welvin21 and @98sean98 will help

**Comment by janvisharma** [comment]
hmmm what about adding href="/#" ?

**Comment by janvisharma** [comment]
and i was thinking of having a component like TeamMemberList and ProjectCardList which would be rendered in App.js instead of rendering individual cards in App.js, how does that sound

**Comment by 98sean98** [comment]
> hmmm what about adding href="/#" ?

I read a couple of threads on stackoverflow. It doesn't seem like a good practice either. Here's a good [guide](https://stackoverflow.com/questions/134845/which-href-value-should-i-use-for-javascript-links-or-javascriptvoid0/8525002#8525002) for using `button` elements instead. And a long thread discussing about this [issue](https://stackoverflow.com/questions/134845/which-href-value-should-i-use-for-javascript-links-or-javascriptvoid0). Both are actually from the same place.

For better code modularity you can use [styled-components](https://styled-components.com/) to first design a `button` element that achieves the desired styling, then import and use in multiple places.

Or you can use libraries like material-ui, react-bootstrap, etc., and use their link / button components to get what you want.

**Comment by 98sean98** [comment]
Closed as stale issue.
